<a href="https://colab.research.google.com/github/Veyis1/Hello/blob/main/Numpy_2_sinif.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:120%; text-align:center; border-radius:10px 10px;">Way to Reinvent Yourself</p>

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="700" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 01</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays (Part-01)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [WHAT IS NUMPY? & WHY DO WE NEED IT?](#00)
* [INSTALLATION INSTRUCTIONS](#0)
* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#1)
* [NUMPY ARRAYS](#2)
    * [Why NumPy?](#2.1)
* [CREATING NUMPY ARRAYS](#3)
    * [From a Python List](#3.1)
* [BUILT-IN METHODS](#4)
    * ["arange"](#4.1)
    * ["linspace"](#4.2)
    * ["zeros", "ones" & "full"](#4.3)
    * ["eye"](#4.4)
    * [Random Built-in Methods](#4.5)
        * ["rand"](#4.5.1)
        * ["randn"](#4.5.2)
        * ["randint"](#4.5.3)    
* [ARRAY ATTRIBUTES & METHODS](#5) 
    * ["reshape"](#5.1)
    * ["max", "min", "argmax" & "argmin"](#5.2)
* [SOME OTHER ATTRIBUTES](#6)        
    * ["shape"](#6.1)
    * ["dtype"](#6.2)
    * ["ndim"](#6.3)
    * ["size"](#6.4)
* [THE END OF THE SESSION-01 (PART-01)](#7)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">What is Numpy? & Why Do We Need It?</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


## What is NumPy? 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

NumPy or Numeric Python is a package for computation on **homogenous n-dimensional arrays**. In numpy dimensions are called as axes.

**Why do we need NumPy?**

A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly. For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

### Numpy is/has;

**POWERFUL N-DIMENSIONAL ARRAYS**<br>
Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.<br>
**NUMERICAL COMPUTING TOOLS**<br>
NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.<br>
**INTEROPERABLE**<br>
NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.<br>
**PERFORMANT**<br>
The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.<br>
**EASY TO USE**<br>
NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.<br>
**OPEN SOURCE**<br>
Distributed under a liberal BSD license, NumPy is developed and maintained publicly on GitHub by a vibrant, responsive, and diverse community. [Source](https://numpy.org/)<br>


## Why do we need it?
To make a logical and mathematical computation on array and matrices, it is needed. It performs these operations way too efficiently and faster than python lists.

## Advantages of NumPy
1. Numpy arrays take less space.
The core of Numpy is its arrays. One of the main advantages of using Numpy arrays is that they take less memory space and provide better runtime speed when compared with similar data structures in python(lists and tuples).NumPy’s arrays are smaller in size than Python lists. A python list could take upto 20MB size while an array could take 4MB. Arrays are also easy to access for reading and writing.
2. The speed performance is also great. It performs faster computations than python lists.
3. Numpy support some specific scientific functions such as linear algebra. They help us in solving linear equations.
4. Numpy support vectorized operations, like elementwise addition and multiplication, computing Kronecker product, etc. Python lists fail to support these features.
5. It is a very good substitute for MATLAB, OCTAVE, etc as it provides similar functionalities and supports with faster development and less mental overhead(as python is easy to write and comprehend)
6. As it is open-source, it doesn’t cost anything, and it uses a very popular programming language, Python, which has high-quality libraries for almost every task. Also, it is easy to connect the existing C code to the Python interpreter.
7. NumPy is very good for data analysis.

## Disadvantages of NumPy

1. Using “nan” in Numpy: “Nan” stands for “not a number”. It was designed to address the problem of missing values. NumPy itself supports “nan” but lack of cross-platform support within Python makes it difficult for the user. That’s why we may face problems when comparing values within the Python interpreter.
2. Require a contiguous allocation of memory: Insertion and deletion operations become costly as data is stored in contiguous memory locations as shifting it requires shifting.

![Capture1.PNG](https://i.ibb.co/FY1q7Xh/uses-of-numpy.png)

[Numpy Source 01](https://www.educba.com/what-is-numpy-in-python/),
[Numpy Source 02](https://www.javatpoint.com/numpy-tutorial),
[Numpy Source 03](https://techvidvan.com/tutorials/python-numpy-tutorial/),
[Numpy Source 04](https://medium.com/analytics-vidhya/introduction-to-numpy-16a6efaffdd7),
[Numpy Source 05](https://data-flair.training/blogs/python-numpy-tutorial/),
[Numpy Source 06](https://www.quora.com/In-Python-what-is-NumPy-How-is-it-used),
[Numpy Source 07](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html),
[Numpy Source 08](https://towardsdatascience.com/a-hitchhiker-guide-to-python-numpy-arrays-9358de570121),
[Numpy Source 09](https://scipy-lectures.org/intro/numpy/array_object.html),
[Numpy Source 09](https://www.educba.com/introduction-to-numpy/)

We will only learn the basics of NumPy, to get started we need to install it!

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Installation Instructions</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [3]:
import numpy as np
import time
import sys

In [1]:
listem = [3, "üç", True, 6.0, (1,2,3), {"1" : 1, "2" : 2 }]

for i in range(len(listem)):
    print(f"data : {listem[i]} : type : {type(listem[i])}")

data : 3 : type : <class 'int'>
data : üç : type : <class 'str'>
data : True : type : <class 'bool'>
data : 6.0 : type : <class 'float'>
data : (1, 2, 3) : type : <class 'tuple'>
data : {'1': 1, '2': 2} : type : <class 'dict'>


In [4]:
listem_tektip =[1,2,3]
np.array(listem_tektip)

array([1, 2, 3])

In [5]:
listem2 =[1,2.0,3]
np.array(listem2)

array([1., 2., 3.])

In [6]:
np.array(listem2).dtype

dtype('float64')

In [14]:
listem3 =[1,'2',3.0]
array3= np.array(listem3).dtype
array3# str kapsayici 


dtype('<U32')

In [ ]:
listem = [3, "üç", True, 6.0, (1,2,3), {"1" : 1, "2" : 2 }]

In [16]:
np.array(listem)

<ipython-input-16-031c61082637>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(listem)


array([3, 'üç', True, 6.0, (1, 2, 3), {'1': 1, '2': 2}], dtype=object)

In [22]:
arr= np.array(['a','b','3'],dtype='i')

ValueError: ignored

In [21]:
arr= np.array(['a','b','3'], dtype= 'O')
arr

array(['a', 'b', '3'], dtype=object)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

In [23]:
d3 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]])
d3# 3 boyutlu matris  en distaki parantez sayisi bize arrayin boyutunu veriri bu 3 boyutludur icinde 2 dimetin var birde disindaki [] ler olunca 3 boyutlu olur

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [25]:
d3.shape # 2 tane 4'e 3'luk  matris demek 

(2, 4, 3)

In [ ]:
#pip install numpy

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Arrays</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

![Capture2.PNG](https://i.ibb.co/bP4S9Tq/numpy-ndarray.png)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Why NumPy?</p>

<a id="2.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

![Numpy_vs_Lists](https://i.ibb.co/Lr0zQ1p/Numpy-vs-Lists.png)

[Numpy Array vs List Source 01](https://blog.finxter.com/what-are-advantages-of-numpy-over-regular-python-lists/),
[Numpy Array vs List Source 02](https://numpy.org/doc/stable/user/whatisnumpy.html),
[Numpy Array vs List Source 03](https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6),
[Numpy vs List Source 04](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.),
[Numpy Array vs List Source 05](https://dev.to/chanduthedev/python-list-vs-numpy-array-3pjp),
[Numpy Array vs List Source 06](https://medium.com/analytics-vidhya/list-vs-numpy-comparision-35bf921588e9),
[Numpy Array vs List Source 07](https://stackoverflow.com/questions/15944171/python-differences-between-lists-and-numpy-array-of-objects),
[Numpy Array vs List Video Source 01](https://www.youtube.com/watch?v=mkbgEvUkSaM),
[Numpy Array vs List Video Source 02](https://www.youtube.com/watch?v=JtW_xGNDEJ8) &
[Numpy Array vs List Video Source 03](https://www.youtube.com/watch?v=C10KmAbCW6A)

**Let's begin our introduction by exploring how to create NumPy arrays.**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Creating Numpy Arrays</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

An array is a collection of items stored at contiguous memory locations. The idea is to store multiple items of the same type together. This makes it easier to calculate the position of each element by simply adding an offset to a base value, i.e., the memory location of the first element of the array (generally denoted by the name of the array).<br>
Array can be handled in Python by a module named array. They can be useful when we have to manipulate only a specific data type values. A user can treat lists as arrays. However, user cannot constraint the type of elements stored in a list. If you create arrays using the array module, all elements of the array must be of the same type.<br>
Array in Python can be created by importing array module. **array(data_type, value_list)** is used to create an array with data type and value list specified in its arguments.<br>

[Numpy Array Source 01](https://www.geeksforgeeks.org/python-arrays/),
[Numpy Array Source 02](https://thispointer.com/python-numpy-create-a-ndarray-from-list-tuple-or-list-of-lists-using-numpy-array/),
[Numpy Array Source 03](https://www.pluralsight.com/guides/different-ways-create-numpy-arrays),
[Numpy Array Source 04](https://stackoverflow.com/questions/33983053/how-to-create-a-numpy-array-of-lists/33987165),
[Numpy Array Source 05](https://towardsdatascience.com/the-ten-best-ways-to-create-numpy-arrays-8b1029a972a7),
[Numpy Array Source 06](https://blog.finxter.com/how-to-convert-a-list-to-a-numpy-array/),
[Numpy Array Video Source 01](https://youtu.be/MKOw9ATtVqE),
[Numpy Array Video Source 02](https://youtu.be/RQ0x6OHym3k)

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">From a Python List</p>

<a id="3.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

We can create an array by directly converting a list or list of lists:

In [26]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [27]:
np.__version__

'1.22.4'

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Built-in Methods</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**There are lots of built-in ways to generate Arrays. Let us examine the most important ones:**

In [28]:
my_list=[1,2,3]
my_list


[1, 2, 3]

In [31]:
my_array= np.array(my_list)
my_array

array([1, 2, 3])

In [43]:
my_list2=[[1,2,3,4],[1,2,3,4],[1,2,3,4]]

In [44]:
my_list2

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]

In [45]:
my_array2= np.array(my_list2)
my_array2

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"arange"</p>

<a id="4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Return evenly spaced values within a given interval.

arange([start,] stop[, step,], dtype=None)

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [39]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"linspace"</p>

<a id="4.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>
Return evenly spaced numbers over a specified interval.

np.linspace(start, stop, num=50)

In [49]:
np.linspace(0,10,3)# normalde 10 dahil edilmez ama linspace 10 dahil oluyor. 0 dan 10 3 tane esit aralikli rakam uret diyoruz 

array([ 0.,  5., 10.])

In [48]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [50]:
np.linspace(0,10,3, endpoint =False) #endpoint ile esit bolme islemi iptal edildi 

array([0.        , 3.33333333, 6.66666667])

In [52]:
np.linspace(0,10,51,dtype=int) # 51 esit aralik sayi var dtype ile sonucu integere cevirdik 

array([ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,
        3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  6,
        6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"zeros", "ones" & "full</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Generate arrays of zeros or ones

np.zeros(shape, dtype=float, order='C')

np.ones(shape, dtype=None, order='C')

np.full(shape, fill_value, dtype=None, order='C')

In [56]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [57]:
np.ones((5,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"eye"</p>

<a id="4.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Creates an [identity matrix](https://www.mathbootcamps.com/the-identity-matrix-and-its-properties/)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Random Built-in Methods</p>

<a id="4.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy also has lots of ways to create random number arrays:


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"rand"</p>

<a id="4.5.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

- ``(0, 5)`` = 1, 2, 3, 4
- ``(0, 5]`` = 1, 2, 3, 4, 5
- ``[0, 5)`` = 0, 1, 2, 3, 4
- ``[0, 5]`` = 0, 1, 2, 3, 4, 5

In [62]:
np.random.randn(2)# 1 boyutlu shapesi 2 olan bir dizi uretti

array([-0.31933053,  1.43497706])

In [63]:
np.random.randn(5,5)

array([[-0.06282584,  0.91094609,  1.68996713,  0.44328956, -0.28867267],
       [ 0.96087494,  0.71175852,  0.77693183,  2.54645408, -1.58589102],
       [ 1.62423134,  2.24619441,  1.33179906,  0.14965437, -1.00922661],
       [ 2.79468684,  0.5955674 , -1.11832046, -1.63617517, -0.22826148],
       [ 0.73185146, -0.30571739,  0.59174503,  0.22291958,  1.61876467]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"randn"</p>

<a id="4.5.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [64]:
np.random.randn(2)

array([0.13314879, 1.07127419])

In [65]:
np.random.randn(5,5)

array([[ 0.87959731, -0.56482951, -0.93255636, -0.72360226,  0.06554311],
       [-1.06599854,  1.9072004 , -0.30804397, -0.81641621,  0.44309522],
       [-0.64474847,  1.23651659,  0.75995877,  1.15169896, -0.91358119],
       [ 1.16991076, -1.3611536 , -0.20713975, -0.04035115,  1.66378683],
       [-1.34798804,  0.99799297,  0.90353906,  2.27206941,  0.59512059]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"randint"</p>

<a id="4.5.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Return random integers from `low` (inclusive) to `high` (exclusive).

randint(low, high=None, size=None, dtype=int)

In [69]:
np.random.randint(10,52,10)# rasgele sayi uretir

array([39, 12, 47, 51, 41, 39, 48, 44, 12, 51])

In [70]:
np.random.randint(5, size=(2,4))

array([[3, 2, 4, 3],
       [0, 0, 2, 2]])

In [90]:
np.random.randint([3,5,10]) # 3 : 0 ve 3 arasi sayi üretir . 0-5 arasi bir sayi üretir . 0-10 arasi bir sayi üretir

array([1, 4, 2])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">ARRAY ATTRIBUTES & METHODS</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Let's discuss some useful attributes and methods or an array:

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"reshape"</p>

<a id="5.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Returns an array containing the same data with a new shape.

In [74]:
arr =np.arange(36)    
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"max", "min", "argmax" & "argmin"</p>

<a id="5.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:center; border-radius:10px 10px;">SOME OTHER ATTRIBUTES</p>

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

* ``shape``: tuple of array dimensions.
* ``size``: Number of elements in the array.
* ``ndim``: number of array dimensions.
* ``itemsize``: the size in bytes of each element of the array.
* ``dtype``: data types of the array.



### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"shape"</p>

<a id="6.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Shape is an attribute that arrays have (not a method):

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"dtype"</p>

<a id="6.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

You can also grab the data type of the object in the array:

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"ndim"</p>

<a id="6.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">"size"</p>

<a id="6.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:150%; text-align:center; border-radius:10px 10px;">The End of the NumPy Session-01 (Part-01)</p>

<a id="7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>
___